-- ═══════════════════════════════════════════════════════════════════════════
-- OBSOLETO — no ejecutar este archivo.
-- ═══════════════════════════════════════════════════════════════════════════
--
-- El esquema vive ahora en migraciones numeradas e idempotentes:
--
--     backend/sql/migrations/001_esquema_base.sql .. 008_rls.sql
--
-- Instrucciones de ejecución, dependencias y reversión:
--
--     backend/sql/README.md
--
-- El script original se conserva en backend/sql/legacy/init.sql únicamente
-- como referencia histórica. No era idempotente y tenía tres defectos que
-- las migraciones corrigen: faltaba epm_sessions.user_name, faltaba el índice
-- único sobre epm_actividades.session_id, y los campos numéricos y de fecha
-- estaban declarados como TEXT.
-- ═══════════════════════════════════════════════════════════════════════════
